stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "22.16.0"
  DOCKER_DRIVER: overlay2

# Cache node_modules
cache:
  paths:
    - node_modules/
    - .next/cache/

# Test stage
test:
  stage: test
  tags:
    - dongl
  image: node:${NODE_VERSION}-alpine
  script:
    - npm ci
    - npm run lint
    - npm run type-check
    - npm run test
  only:
    - merge_requests
    - main
    - develop
    - staging
    - uat
